/*
 * This file was generated by RedG.
 * https://yamass.github.io/redg
 * DO NOT EDIT MANUALLY!
 * Re-run the code generation to reflect database changes.
 */
package com.example;

import java.util.ArrayList;
import java.util.List;

import de.yamass.redg.runtime.*;
import de.yamass.redg.models.*;

/**
 * my_enum
 */
public enum my_enum {
    A("A"),
    B("B"),
    C("C");

    String literal;

    public my_enum(String literal) {
        this.literal = literal;
    }
}