-- Test

create type my_enum as enum ('A', 'B', 'C');

CREATE TABLE DEMO_COMPANY (
  ID   NUMBER(19)        NOT NULL,
  NAME VARCHAR2(30 CHARACTERS) NOT NULL,
  ENUM_VALUE my_enum,

  CONSTRAINT pk_DEMO_COMPANY PRIMARY KEY (ID)
);

CREATE TABLE DEMO_USER (
  DTYPE      VARCHAR2(32 CHARACTERS) NOT NULL,
  ID         NUMBER(19)        NOT NULL,
  USERNAME   VARCHAR2(30 CHARACTERS) NOT NULL,
  FIRST_NAME VARCHAR2(50 CHARACTERS),
  LAST_NAME  VARCHAR2(50 CHARACTERS),
  WORKS_AT   NUMBER(19)        NOT NULL,
  DAY_TS        timestamp,

  CONSTRAINT pk_DEMO_USER PRIMARY KEY (ID),
  CONSTRAINT fk_DEMO_USER_COMPANY FOREIGN KEY (WORKS_AT) REFERENCES DEMO_COMPANY(ID)
);

