
CREATE TABLE DEMO_COMPANY (
  ID   NUMBER(19)        PRIMARY KEY,
  NAME VARCHAR2(30 CHARACTERS) NOT NULL
);

CREATE TABLE DEMO_USER (
  ID         NUMBER(19)        PRIMARY KEY,
  USERNAME   VARCHAR2(30 CHARACTERS) NOT NULL,
  FIRST_NAME VARCHAR2(50 CHARACTERS),
  LAST_NAME  VARCHAR2(50 CHARACTERS)
);

CREATE TABLE USER_WORKS_AT_COMPANIES (
  ID NUMBER(19) PRIMARY KEY ,
  USER_ID NUMBER(19) NOT NULL ,
  COMPANY_ID NUMBER(19) NOT NULL ,

  CONSTRAINT FK_WORKS_AT_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES DEMO_COMPANY(ID),
  CONSTRAINT FK_USER_WORKS FOREIGN KEY (USER_ID) REFERENCES DEMO_USER(ID)
);

create or replace view X as (select USERNAME from DEMO_USER);