-- Test

CREATE TABLE EXCHANGE_REF (
  ID   NUMBER(19)        PRIMARY KEY, -- 1
  NAME VARCHAR2(30 CHARACTERS) NOT NULL -- Lea
);

CREATE TABLE EXCHANGE_RATE (
  ID              NUMBER(19)        PRIMARY KEY, -- 11, 12
  REFERENCE_ID    NUMBER(19)        NOT NULL, -- 1, 1
  FIRST_NAME      VARCHAR2(50 CHARACTERS), -- Flo1, Flo2
  PREV_FIRST_NAME VARCHAR2(50 CHARACTERS), -- null, Flo1

  CONSTRAINT UNIQ_EXCHANGE_RATE_REF_PREV_FIRST_NAME UNIQUE (REFERENCE_ID, FIRST_NAME),
  CONSTRAINT fk_EXCHANGE_RATE_COMPOSITE FOREIGN KEY (REFERENCE_ID, PREV_FIRST_NAME) REFERENCES EXCHANGE_RATE(REFERENCE_ID, FIRST_NAME),
  CONSTRAINT fk_EXCHANGE_REF_REFERING FOREIGN KEY (REFERENCE_ID) REFERENCES EXCHANGE_REF(ID)
);

-- alter table EXCHANGE_RATE add constraint FK_EXRATE_REF foreign key(REFERENCE_ID, PREV_END) references EXCHANGE_RATE(REFERENCE_ID, INTERVAL_END);


